
services:
  app:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${IMAGE_NAME:-username/test-cd-app}:${TAG:-latest}
    container_name: ${CONTAINER_NAME:-test-cd-app}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - deployment.env
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEPLOYMENT=${DEPLOYMENT_SHA:-local}
      - PORT=${PORT:-3000}
      - HOST=${HOST:-0.0.0.0}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "deployment.environment=${APP_ENV:-development}"
      - "deployment.date=${DEPLOYMENT_DATE:-unknown}"
      - "deployment.sha=${DEPLOYMENT_SHA:-unknown}"
      - "app.name=${APP_NAME:-test-cd-app}"
      - "app.version=${APP_VERSION:-1.0.0}"
